name: Kotlin CI (sin build tool)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Install Kotlin
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin
          echo 'source "$HOME/.sdkman/bin/sdkman-init.sh"' >> $GITHUB_ENV
      - name: Compile
        shell: bash
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          find src -name "*.kt" > sources.txt
          kotlinc @sources.txt -include-runtime -d app.jar
      - name: Run
        run: java -jar app.jar
      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: app.jar
          if-no-files-found: error
