name: Kotlin CI (sin build tool)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Install Kotlin compiler
        run: sudo apt-get update && sudo apt-get install -y kotlin
      - name: Compile
        run: kotlinc src -include-runtime -d app.jar
      - name: Run
        run: java -jar app.jar
      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: app.jar
          if-no-files-found: error
